DESCRIPTIONS = {
    "ServerConfig.title": "Título que ve la audiencia en la página principal.",
    "ServerConfig.host": "Interfaz donde escucha el servidor. 0.0.0.0 = todas.",
    "ServerConfig.port": "Puerto HTTP/WebSocket.",
    "ServerConfig.admin_token": "Token para el panel, la API de administración y la ingesta. Vacío = sin autenticación (solo para pruebas locales).",
    "ServerConfig.public_url": "URL pública (https://subs.mievento.org) usada en los QR y en el banner. Vacío = la URL con la que entra cada cliente.",
    "ServerConfig.data_dir": "Directorio de persistencia: transcripciones JSONL por sala y sesiones creadas desde el panel.",
    "ServerConfig.cors_origins": "Orígenes permitidos para CORS (si otro sitio consume la API).",
    "ServerConfig.history_size": "Subtítulos recientes que recibe un visor al conectarse.",
    "VadConfig.frame_ms": "Tamaño de la ventana de análisis en ms.",
    "VadConfig.min_silence_ms": "Silencio necesario para cerrar una frase. Menos = frases más cortas y rápidas.",
    "VadConfig.min_segment_s": "Duración mínima de un segmento antes de cerrarlo por silencio.",
    "VadConfig.max_segment_s": "Duración máxima; al llegar se corta en la última pausa detectada.",
    "VadConfig.pre_roll_ms": "Audio previo al inicio de voz que se incluye para no cortar la primera sílaba.",
    "VadConfig.speech_threshold_db": "dB por encima del piso de ruido adaptativo para considerar voz.",
    "VadConfig.min_speech_dbfs": "Nivel absoluto mínimo (dBFS) para considerar voz.",
    "VadConfig.min_speech_ms": "Segmentos con menos voz que esto se descartan (ruidos, aplausos cortos).",
    "GeminiConfig.api_key": "API key de Google AI Studio. Vacío = usar GEMINI_API_KEY o GOOGLE_API_KEY del entorno.",
    "GeminiConfig.vertexai": "Usar Vertex AI (credenciales de Google Cloud) en lugar de API key.",
    "GeminiConfig.project": "Proyecto de Google Cloud (solo Vertex AI).",
    "GeminiConfig.location": "Región de Vertex AI, por ejemplo us-central1.",
    "LiveSessionConfig.rotate_after_s": "Desde este momento se busca una pausa del orador para abrir una sesión nueva.",
    "LiveSessionConfig.rotate_deadline_s": "Se rota sí o sí al llegar aquí, aunque el orador siga hablando.",
    "LiveSessionConfig.rotate_quiet_ms": "Cuánto silencio cuenta como pausa para rotar.",
    "LiveSessionConfig.drain_timeout_s": "Espera máxima de los últimos finales al rotar o detener.",
    "LiveSessionConfig.idle_close_s": "Sin audio durante este tiempo se cierra la sesión Live; se reabre sola al volver el audio.",
    "LiveSessionConfig.reconnect_backoff_s": "Espera inicial antes de reconectar tras un error.",
    "LiveSessionConfig.reconnect_backoff_max_s": "Espera máxima entre reintentos (crece exponencialmente).",
    "GeminiLiveConfig.rotate_after_s": "Desde este momento se busca una pausa del orador para abrir una sesión nueva.",
    "GeminiLiveConfig.rotate_deadline_s": "Se rota sí o sí al llegar aquí, aunque el orador siga hablando.",
    "GeminiLiveConfig.rotate_quiet_ms": "Cuánto silencio cuenta como pausa para rotar.",
    "GeminiLiveConfig.drain_timeout_s": "Espera máxima de los últimos finales al rotar o detener.",
    "GeminiLiveConfig.idle_close_s": "Sin audio durante este tiempo se cierra la sesión Live; se reabre sola al volver el audio.",
    "GeminiLiveConfig.reconnect_backoff_s": "Espera inicial antes de reconectar tras un error.",
    "GeminiLiveConfig.reconnect_backoff_max_s": "Espera máxima entre reintentos (crece exponencialmente).",
    "GeminiLiveConfig.asr_model": "Modelo de transcripción en streaming del Live API.",
    "GeminiLiveConfig.mode": "SMART = puntuación y sin muletillas (mejor para subtítulos); VERBATIM = literal.",
    "GeminiLiveConfig.emit_partials": "Mostrar hipótesis parciales mientras el orador habla (latencia sub-segundo en el idioma original).",
    "GeminiLiveConfig.start_sensitivity": "Sensibilidad del inicio de voz del VAD del modelo.",
    "GeminiLiveConfig.end_sensitivity": "Sensibilidad del fin de voz: high cierra frases antes (más rápido, más cortas).",
    "GeminiLiveConfig.silence_duration_ms": "Silencio que el modelo considera fin de frase. Vacío = valor del modelo.",
    "GeminiLiveConfig.prefix_padding_ms": "Audio previo que el modelo conserva al detectar inicio de voz. Vacío = valor del modelo.",
    "GeminiLiveConfig.final_chunk_timeout_s": "Los finales llegan en trozos: si el trozo termina una oración, se confirma tras esta espera sin novedades.",
    "GeminiLiveConfig.final_chunk_max_wait_s": "Si el trozo quedó a mitad de oración, se espera hasta esto por el resto antes de confirmar.",
    "GeminiLiveTranslateConfig.rotate_after_s": "Desde este momento se busca una pausa del orador para abrir una sesión nueva.",
    "GeminiLiveTranslateConfig.rotate_deadline_s": "Se rota sí o sí al llegar aquí, aunque el orador siga hablando.",
    "GeminiLiveTranslateConfig.rotate_quiet_ms": "Cuánto silencio cuenta como pausa para rotar.",
    "GeminiLiveTranslateConfig.drain_timeout_s": "Espera máxima de los últimos finales al rotar o detener.",
    "GeminiLiveTranslateConfig.idle_close_s": "Sin audio durante este tiempo se cierra la sesión Live; se reabre sola al volver el audio.",
    "GeminiLiveTranslateConfig.reconnect_backoff_s": "Espera inicial antes de reconectar tras un error.",
    "GeminiLiveTranslateConfig.reconnect_backoff_max_s": "Espera máxima entre reintentos (crece exponencialmente).",
    "GeminiLiveTranslateConfig.model": "Modelo de traducción en vivo del Live API.",
    "GeminiLiveTranslateConfig.echo_target_language": "Si el orador ya habla en el idioma destino, pasar su voz/texto sin traducir.",
    "GeminiLiveTranslateConfig.stream_audio": "Retransmitir el audio traducido (PCM 24 kHz) por /ws/audio/<sala> para escucharlo en el visor.",
    "GeminiChunkedConfig.model": "Modelo multimodal que recibe el audio.",
    "GeminiChunkedConfig.vad": "Segmentación por energía.",
    "GeminiChunkedConfig.max_inflight": "Segmentos procesándose en paralelo por sala.",
    "GeminiChunkedConfig.timeout_s": "Timeout por llamada.",
    "LocalConfig.whisper_model": "Tamaño de Whisper: tiny | base | small | medium | large-v3 | large-v3-turbo | distil-large-v3.",
    "LocalConfig.device": "auto (GPU si hay CUDA, si no CPU) | cpu | cuda.",
    "LocalConfig.compute_type": "Precisión de CTranslate2: default | int8 | float16 | int8_float16.",
    "LocalConfig.beam_size": "Beam search; 1 = más rápido, 5 = algo mejor y más lento.",
    "LocalConfig.vad": "Segmentación por energía.",
    "LocalConfig.max_inflight": "Segmentos en paralelo por sala (la GPU es el límite).",
    "TranslatorConfig.provider": "gemini (nube) | ollama (local, Gemma) | mock (pruebas) | none (solo transcribir).",
    "TranslatorConfig.model": "Modelo: gemini-3.5-flash-lite, o para Ollama gemma4:e4b / gemma4:12b.",
    "TranslatorConfig.ollama_url": "URL del servidor Ollama.",
    "TranslatorConfig.context_size": "Frases previas que se pasan como contexto (más = mejor coherencia, más tokens).",
    "TranslatorConfig.max_concurrency": "Traducciones simultáneas en todo el proceso (protege la cuota con muchas salas).",
    "TranslatorConfig.timeout_s": "Timeout por traducción.",
    "TranslatorConfig.thinking": "off desactiva el razonamiento del modelo (más rápido y barato).",
    "TranslatorConfig.temperature": "Creatividad del traductor; bajo = literal y estable.",
    "EnginesConfig.gemini_live": "Ajustes del motor gemini-live.",
    "EnginesConfig.gemini_live_translate": "Ajustes del motor gemini-live-translate.",
    "EnginesConfig.gemini_chunked": "Ajustes del motor gemini-chunked.",
    "EnginesConfig.local": "Ajustes del motor local.",
    "SessionDefaults.engine": "Motor: gemini-live | gemini-live-translate | gemini-chunked | local | mock.",
    "SessionDefaults.source_language": "Idioma que se habla (en, es, pt…) o auto para detectarlo por frase.",
    "SessionDefaults.target_languages": "Idiomas a los que se traduce. Un destino igual al idioma detectado se muestra sin traducir.",
    "SessionDefaults.glossary": "Nombres propios, sponsors, tecnologías: se pasan como vocabulario al ASR y no se traducen.",
    "SessionDefaults.language_notes": "Instrucciones de estilo por idioma destino para el traductor.",
    "SessionDefaults.translator": "Traductor por defecto para las salas (si no, el `translator` global).",
    "SessionConfig.id": "Identificador para las URLs: minúsculas, números, guiones (sala-a).",
    "SessionConfig.name": "Nombre visible para la audiencia.",
    "SessionConfig.source": "Fuente de audio: browser | rtmp://… | srt://… | https://…m3u8 | pulse:default | alsa:hw:0 | archivo | ffmpeg:<args>.",
    "SessionConfig.source_args": "Argumentos extra de entrada para ffmpeg.",
    "SessionConfig.loop": "Repetir archivos en bucle (demos).",
    "SessionConfig.engine": "Motor de esta sala (si no, defaults.engine).",
    "SessionConfig.source_language": "Idioma hablado en esta sala (si no, defaults.source_language). auto = detectar.",
    "SessionConfig.target_languages": "Idiomas destino de esta sala (si no, defaults.target_languages).",
    "SessionConfig.glossary": "Términos adicionales a los de defaults.glossary.",
    "SessionConfig.translator": "Traductor propio de esta sala (por ejemplo ollama para una sala 100 % local).",
    "SessionConfig.autostart": "Arrancar con el servidor. false = queda creada y se inicia desde el panel.",
    "AppConfig.latency_profile": "fast = frases cortas y rápidas; balanced = equilibrio; quality = frases completas, mejor traducción. Ajusta los parámetros de latencia que no estén fijados a mano (docs/LATENCIA.md).",
    "AppConfig.server": "Servidor web.",
    "AppConfig.gemini": "Credenciales de Gemini.",
    "AppConfig.engines": "Ajustes por motor.",
    "AppConfig.translator": "Traductor de texto global.",
    "AppConfig.defaults": "Valores por defecto de las salas.",
    "AppConfig.sessions": "Salas. También se pueden crear en caliente desde el panel (se persisten en data_dir/sessions.json).",
}

SECTION_NOTES = {
    "AppConfig": "Raíz del archivo de configuración.",
    "ServerConfig": "Servidor web: puertos, autenticación, persistencia.",
    "GeminiConfig": "Credenciales de Gemini (API key de AI Studio o Vertex AI).",
    "EnginesConfig": "Ajustes de cada motor. Solo hace falta tocar el que se usa.",
    "GeminiLiveConfig": "Motor `gemini-live`: transcripción en streaming + traductor de texto. Hereda el ciclo de vida de sesiones Live (rotación, drenaje, inactividad).",
    "GeminiLiveTranslateConfig": "Motor `gemini-live-translate`: un solo modelo, voz → voz traducida + transcripciones.",
    "GeminiChunkedConfig": "Motor `gemini-chunked`: segmentos WAV → generate_content (transcribe y traduce en una llamada).",
    "VadConfig": "Detector de actividad de voz por energía, usado por los motores por segmentos (gemini-chunked, local, mock).",
    "LocalConfig": "Motor `local`: faster-whisper para transcribir + Ollama (Gemma) para traducir.",
    "TranslatorConfig": "Traductor de texto usado por gemini-live, gemini-chunked (destinos extra) y local.",
    "SessionDefaults": "Valores por defecto para todas las salas; cada sala puede pisarlos.",
    "SessionConfig": "Una sala.",
}
